ReconnectClientFactory
beanstalkd/pybeanstalk pull request #27
Opened 2018-01-07 08:49 UTC by guntanis

The current implementation of the ClientFactory doesn't support reconnects, this implements ReconnectingClientFactory and the necessary methods.

Can be implemented in Twisted like this:
    queueClient = beanstalk.twisted_client.BeanstalkClientFactory(
        reactor,
        beanstalk.twisted_client.Beanstalk(),
        generatorClass(params).worker
    )

2018-01-24 16:40 UTC, sophacles requested changes
Hi thanks for the submission! The tests aren't passing, probably due to not having `ReconnectingClientFactory` imported.

Also, not sure what the reconnecting factory give us here, and if we need to change anything else to deal with loss of connection, can you expand on why this is an improvement a bit, or point me to resources to understand better?

2018-01-24 16:40 UTC, sophacles commented on beanstalk/twisted_client.py
> +class BeanstalkClientFactory(ReconnectingClientFactory):
Looks like the ReconnectingClientFactory needs to be imported from... twisted?

2018-01-24 16:40 UTC, sophacles commented on beanstalk/twisted_client.py
> +            p
Typo or unfinished necessary code?

2019-08-14 07:13 UTC, closed without merging

2019-08-16 11:13 UTC, ysmolsky commented
@sophacles do you maintain this repo or should I archive it?